language: ruby
rvm:
  - 2.6.0
services:
  - postgresql
before_script:
  - RAILS_ENV=test bundle exec rake db:create
deploy:
  provider: rubygems
  api_key: $RUBY_GEMS_API_KEY
  on:
    branch: master
